name: riverpod_navigator_go_router
description: go_router examples
version: 0.1.0
homepage: https://github.com/PavelPZ/riverpod_navigator
repository: https://github.com/PavelPZ/riverpod_navigator
publish_to: 'none'

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  freezed_annotation: ^1.1.0
  hooks_riverpod: ^1.0.0
  json_annotation: ^4.4.0
  meta: ^1.7.0
  riverpod: ^1.0.0
  riverpod_navigator:
    path: ../../packages/riverpod_navigator
  tuple: ^2.0.0

dev_dependencies: 
  build_runner:
  flutter_test:
    sdk: flutter
  freezed:
  functional_widget:
  json_serializable:
  mockito:
  test:

flutter:
  uses-material-design: true
