name: riverpod_navigator
description: Simple but powerfull Flutter navigation with riverpod and Navigator 2.0.
version: 0.30.0
homepage: https://github.com/PavelPZ/riverpod_navigator
repository: https://github.com/PavelPZ/riverpod_navigator
publish_to: 'none'

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^1.0.0
  meta: ^1.7.0
  riverpod_navigator_core: # 0.30.0
    path: ../riverpod_navigator_core 

dev_dependencies: 
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
