name: doc
description: Documentation for riverpod navigation
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks:
  hooks_riverpod:
  json_annotation: ^4.4.0
  path:
  riverpod_navigator: 
    path: ../../packages/riverpod_navigator
  riverpod_navigator_core: 
    path: ../../packages/riverpod_navigator_core

dev_dependencies: 
  analyzer: ^3.0.0
  build_runner:
  flutter_test:
   sdk: flutter
  json_serializable:
  test:

dependency_overrides:
  analyzer: ^2.1.0

flutter:
  uses-material-design: true

# https://medium.com/p/c55b627da8a6/edit

# dartdoc
# cd doc\api
# dhttpd
# open http://localhost:8080/index.html

# flutter pub run build_runner watch  --delete-conflicting-outputs

# dart pub publish --dry-run
# dart pub publish
# dart pub publish --force 

# flutter build web --web-renderer html -t lib\async.dart