name: doc
description: Documentation for riverpod navigation
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks:
  freezed_annotation:
  functional_widget_annotation:
  hooks_riverpod:
  json_annotation:
  riverpod_navigator:
    path: ../../packages/riverpod_navigator

dev_dependencies: 
  build_runner:
  flutter_test:
    sdk: flutter
  freezed:
  functional_widget:
  json_serializable:
  test:

flutter:
  uses-material-design: true