name: riverpod_navigator_core
description: Simple but powerfull Flutter navigation with riverpod, freezed and Navigator 2.0.
version: 0.25.0
homepage: https://github.com/PavelPZ/riverpod_navigator
repository: https://github.com/PavelPZ/riverpod_navigator
publish_to: 'none'

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  json_annotation: ^4.4.0
  meta: ^1.7.0
  riverpod: ^1.0.0
  tuple: ^2.0.0

dev_dependencies: 
  lints: ^1.0.1
  test:

flutter:
  uses-material-design: true

# dartdoc
# cd doc\api
# dhttpd
# open http://localhost:8080/index.html

# flutter pub run build_runner watch  --delete-conflicting-outputs

# dart pub publish --dry-run
# dart pub publish
# dart pub publish --force 
