name: riverpod_navigator_core
description: Navigation state management using the riverpod
version: 0.1.0
homepage: https://github.com/PavelPZ/riverpod_navigator
repository: https://github.com/PavelPZ/riverpod_navigator
publish_to: 'none'

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  async:
  json_annotation: ^4.4.0
  meta: ^1.7.0
  riverpod: ^1.0.0
  tuple: ^2.0.0

dev_dependencies: 
  build_runner:
  test:

flutter:
  uses-material-design: true

# dartdoc
# cd doc\api
# dhttpd
# open http://localhost:8080/index.html

# flutter pub run build_runner watch  --delete-conflicting-outputs

# dart pub publish --dry-run
# dart pub publish
# dart pub publish --force 
