name: books_dart
description: books for dart example
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  freezed_annotation:
  json_annotation:
  riverpod:
  riverpod_navigator:
    path: ../../packages/riverpod_navigator

dev_dependencies: 
  build_runner:
  freezed:
  json_serializable:
  mockito:
  test:
