name: riverpod_navigator_dart
description: Dart only part of riverpod_navigator.
  Allows you to test application state and navigation logic without typing a single widget.
version: 0.2.0
homepage: https://github.com/PavelPZ/riverpod_navigator
repository: https://github.com/PavelPZ/riverpod_navigator
# publish_to: 'none'

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  meta: ^1.7.0
  riverpod: ^1.0.0
  tuple: ^2.0.0

dev_dependencies: 
  build_runner:
  freezed:
  json_serializable:
  mockito:
  test:
