name: riverpod_navigator_dart
description: Dart only part of riverpod_navigator.
  Allows you to test application state and navigation logic without typing a single widget.
version: 0.2.0
homepage: https://github.com/PavelPZ/riverpod_navigator
repository: https://github.com/PavelPZ/riverpod_navigator
publish_to: 'none'

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  freezed_annotation:
  json_annotation:
  riverpod:
  tuple:

dev_dependencies: 
  build_runner:
  freezed:
  json_serializable:
  mockito:
  test:
