name: riverpod_navigator_dart
description: Dart only part of riverpod_navigator.
  Navigation logic can be developed and tested in the Dart environment, without typing a single flutter widget.
version: 0.2.2
homepage: https://github.com/PavelPZ/riverpod_navigator
repository: https://github.com/PavelPZ/riverpod_navigator
# publish_to: 'none'
discontinued:

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  freezed_annotation: ^1.1.0
  json_annotation: 
  meta: ^1.7.0
  riverpod: ^1.0.0
  tuple: ^2.0.0

dev_dependencies: 
  build_runner:
  freezed:
  json_serializable: 
  mockito:
  test:
